# Generated by Django 6.0 on 2025-12-09 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=255)),
                ('apellido', models.TextField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('contrasena', models.TextField(max_length=255)),
            ],
        ),
    ]
