# Generated by Django 6.0 on 2025-12-09 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 12, 9)),
            preserve_default=False,
        ),
    ]
