# Generated by Django 6.0 on 2025-12-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_fecha_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='activos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_act', models.TextField(max_length=255)),
                ('simbolo', models.TextField(max_length=255)),
                ('precio_actual', models.FloatField(max_length=1000)),
                ('variacion_diaria', models.FloatField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(max_length=255)),
                ('detalle', models.TextField(max_length=255)),
                ('fecha_mv', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_orden', models.TextField(max_length=255)),
                ('cantidad', models.FloatField(max_length=1000)),
                ('precio_unit', models.FloatField(max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_total', models.FloatField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='transacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_ejecutada', models.FloatField(max_length=1000)),
                ('precio_final', models.FloatField(max_length=1000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
