# Generated by Django 6.0 on 2025-12-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_activos_movimientos_orden_portafolio_transacciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
