# Generated by Django 6.0 on 2025-12-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='fabian_puebla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
