# Generated by Django 6.0 on 2025-12-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_fabian_puebla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fabian_puebla',
        ),
    ]
